KRKNWK-8785: Create sdk-802154
NordicSemiconductor/nRF-IEEE-802.15.4-radio-driver pull request #12
Opened 2021-02-23 18:34 UTC by JakubPegza

This repository contains new structure of sdk-802154(TBD) repository. Along with it changes in:
https://github.com/JakubPegza/zephyr/tree/feature/add_sdk_802154_repo
https://github.com/JakubPegza/sdk-nrfxlib/tree/feature/remove_nrf_802154_sl
are required

2021-02-24 15:42 UTC, AdamZelikNS commented
The serialization platform headers are here in 
`serialization/include/platform/`
This is different from what was finally adopted in [PR#1](https://github.com/pkwiek/hal-nrf-802154/pull/1) into the `hal-nrf-802154` repo, where it looks like this:
`serialization/include/serialization/platform/`
Is this difference intentional?

2021-02-24 15:43 UTC, AdamZelikNS requested changes

2021-02-24 15:43 UTC, AdamZelikNS commented on serialization/src/include/nrf_802154_serialization_crit_sect.h
> + * @file nrf_802154_serialization_crit_sect.h
I found this file to be duplicate. There is `serialization/include/platform/nrf_802154_serialization_crit_sect.h`.
It looks like it needs to be removed from here, as well as a few others:
`serialization/src/include/nrf_802154_spinel_backend.h`
`serialization/src/include/nrf_802154_spinel_backend_callouts.h`
`serialization/src/include/nrf_802154_spinel_log.h`
`serialization/src/include/nrf_802154_spinel_response_notifier.h`

2021-02-24 15:49 UTC, e-rk commented
Are the bare metal examples going to be included in this PR or are they going to be a part of some stage 2 PR?

2021-02-25 08:03 UTC, JakubPegza commented
> The serialization platform headers are here in
> `serialization/include/platform/`
> This is different from what was finally adopted in [PR#1](https://github.com/pkwiek/hal-nrf-802154/pull/1) into the `hal-nrf-802154` repo, where it looks like this:
> `serialization/include/serialization/platform/`
> Is this difference intentional?

Not intentional, but already aligned between these two repositories. Good catch though

2021-02-25 11:20 UTC, JakubPegza commented
> Are the bare metal examples going to be included in this PR or are they going to be a part of some stage 2 PR?

They are missing here yet because I think they were still not merged when I branched off. They will end up in this PR

2021-05-11 06:07 UTC, jciupis commented
Is it OK to close this PR?

2021-05-11 06:13 UTC, JakubPegza commented
Outdated solution, closing

2021-05-11 06:13 UTC, closed without merging